tap "mongodb/brew", trusted: { formulae: ["mongodb-database-tools"] }
tap "nikitabobko/tap"
brew "fastfetch"
brew "fd"
brew "flyctl"
brew "fzf"
brew "gh"
brew "git"
brew "gopls"
brew "lazygit"
brew "lua-language-server"
brew "luacheck"
brew "luarocks"
brew "tree-sitter"
brew "neovim"
brew "powerlevel10k"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "tree-sitter-cli"
brew "mongodb/brew/mongodb-community@5.0", trusted: true
cask "nikitabobko/tap/aerospace", trusted: true
cask "docker-desktop"
cask "dotnet-sdk"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "karabiner-elements"
cask "wezterm"
npm "corepack"
npm "n"
npm "typescript"
